project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub GPU Cluster Onboarding Guide"
  site-url: https://sydney-informatics-hub.github.io/
  navbar:
    logo: fig/usyd-logo.png
  sidebar:
    style: "docked"
    background: white
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Getting Started with the SIH GPU Cluster"
        contents:
        - text: "Introduction to the SIH GPU Cluster"
          href: notebooks/cluster_intro.html
        - text: "Accessing the SIH GPU Cluster"
          href: notebooks/access.html
        - text: "Login"
          href: notebooks/login.html
        - text: "Key Run:ai features"
          href: notebooks/runai_features.html
      - section: "Tutorials"
        contents:
        - text: "Creating a Jupyter Lab workload"
          href: notebooks/jupyter_tutorial.html
        - text: "Creating a Marimo Python workload"
          href: notebooks/marimo_tutorial.html
        - text: "How to transfer data to/from the SIH GPU Cluster"
          href: notebooks/data_transfer.html
        - text: "How to run a terminal using the Command Line Interface (CLI)"
          href: notebooks/CLI.html
        - text: "How to self-install R packages"
          href: notebooks/R_tutorial.html
        - text: "How to run AlphaFold3"
          href: notebooks/alphafold3_guide.html
  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
    include-in-header: 
      - text: |
          <script data-goatcounter="https://sih.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    link-external-newwindow: true
    link-external-icon: true
    toc: true
    css: [lesson.css]
    theme: cosmo
    code-link: true
    code-fold: false
   
